### ISSUE TITLE
Implement write method for MatchMSData class

### ISSUE THREAD

**Issue by hechth** [RECETOX/RIAssigner#10]
Implement a method to store a MatchMSData object with possibly added retention times and indices back to disk using a format supported by matchms.

**Comment by maximskorik** [comment]
@hechth, this has to be postponed until https://github.com/bioconda/bioconda-recipes/pull/28382 is passed. With matchms 0.9.0 comes the `save_as_msp` method that you contributed.

**Comment by martenson** [comment]
@maximskorik the mentioned recipe has just been merged
