### ISSUE TITLE
Creating a Dockerfile for RIAssigner

### ISSUE THREAD

**Issue by kozo2** [RECETOX/RIAssigner#100]
It seems that RIAssigner has strict dependent package versions.
(Therefore, I haven't been able to try running RIAssigner yet.)
Could you tell me what kind of environment you have where RIAssigner runs without any issues?
I would like to Dockerize that.

**Comment by hechth** [comment]
Hi kozo - you can install the package using conda or use the existing biocontainer at: https://biocontainers.pro/tools/riassigner

` docker pull quay.io/biocontainers/riassigner:0.3.3--pyhdfd78af_0`

**Comment by kozo2** [comment]
Hi @hechth, no need to apologize at all. I completely understand that you must be busy.

>  you can install the package using conda or use the existing biocontainer at: https://biocontainers.pro/tools/riassigner

> docker pull quay.io/biocontainers/riassigner:0.3.3--pyhdfd78af_0

Thank you! It worked well! I close this issue.
```
(base) $ docker pull quay.io/biocontainers/riassigner:0.3.3--pyhdfd78af_0
0.3.3--pyhdfd78af_0: Pulling from biocontainers/riassigner
73349e34840e: Pull complete
acab339ca1e8: Pull complete
1ee03f166404: Pull complete
Digest: sha256:a4b56c866a9df417109b67788662226b2d1a58343891f542175f8592ed207cdc
Status: Downloaded newer image for quay.io/biocontainers/riassigner:0.3.3--pyhdfd78af_0
quay.io/biocontainers/riassigner:0.3.3--pyhdfd78af_0
(base) $ docker run -it quay.io/biocontainers/riassigner:0.3.3--pyhdfd78af_0 bash
root@4470769010c5:/# cd
root@4470769010c5:~# pwd
/root
root@4470769010c5:~# python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from RIAssigner.compute import Kovats
>>> from RIAssigner.data import MatchMSData, PandasData
>>>
```
