### ISSUE TITLE
Add filters to MatchMS data to remove spectra with invalid RT & RI

### ISSUE THREAD

**Issue by hechth** [RECETOX/RIAssigner#27]
Spectra which have neither RT nor RI are currently not useable/don't contribute anything to the computations, so should be filtered out after reading the initial file.

**Comment by ElliottJP** [comment]
Options to filter the structures could also include:
molecular weight / monoisotopic mass range 
elements present
bp (predicted) range of compounds

Also, it would be good to be able to set an m/z window for the spectra.

**Comment by hechth** [comment]
@ElliottJP This is mostly a functionality of matchms - this was for reading files only where there might be some invalid RI. Currently, they are handled as `None`, but it would be better to either discard them or not allow reading the file in order to avoid the overhead from dealing with this problem.

**Comment by ElliottJP** [comment]
Depends - we often have spectra without Rt/RI (they can be imputed) that in some cases are used purely for matching.

**Comment by hechth** [comment]
Well the matching is not part of the tool itself so doesn't really need to be respected. It also just makes handling the data a lot easier if the dataframes aren't expected to have missing values
