### ISSUE TITLE
do not rely on filenames for datatype

### ISSUE THREAD

**Issue by martenson** [RECETOX/RIAssigner#67]
xref https://github.com/RECETOX/RIAssigner/blob/main/RIAssigner/cli/LoadDataAction.py#L18
xref https://github.com/RECETOX/RIAssigner/blob/main/RIAssigner/utils.py#L34

Getting the following trace (can be seen in https://umsa.cerit-sc.cz/u/marten/h/gc-prototype-run-1):
```
  File "/usr/local/lib/python3.8/site-packages/RIAssigner/cli/LoadDataAction.py", line 18, in __call__
    setattr(namespace, self.dest, data)
UnboundLocalError: local variable 'data' referenced before assignment
```

Datatype is supplied by Galaxy, other tools can explicitly consume it instead of trying to guess it (this is a better approach no mater who the caller is though).

**Comment by hechth** [comment]
- [ ] Pass filetype as parameter to `MatchMSData` and `PandasData`
- [ ] Add filetype parameter to CLI
