### ISSUE TITLE
How to install from pip?

### ISSUE THREAD

**Issue by cthoyt** [RECETOX/RIAssigner#84]
Conda is pretty problematic as far as reproducibility goes since you have to hack together environments. Ideally, packages can be installed from pip, but this doesn't seem to be documented on the README. Is this possible?

**Comment by martenson** [comment]
This package can be install with pip by running `pip install .`

You can also try the Docker or Singularity containers at https://biocontainers.pro/tools/riassigner.

**Comment by hechth** [comment]
For installation guideline see the 'Installation' section in the readme - there is also a section on how to install the package manually.

Otherwise it would maybe also be possible to host the package via pypi, but that would require additional steps.

**Comment by cthoyt** [comment]
Yes I am explicitly interested in using the standard package installation procedure from PyPI - a package without this won’t be useful/usable to most potential users

**Comment by hechth** [comment]
Thanks for the feedback - yeah, I was considering hosting on PyPI some time ago but then didn't follow up with it - I agree that a large user base uses PyPI exclusively.

I'll have a look and see that we can get the package onto PyPI!

**Comment by hechth** [comment]
@cthoyt the package is now installable via [pip](https://pypi.org/project/RIAssigner/0.3.2/) - can you please confirm everything works fine for you?

**Comment by hechth** [comment]
@cthoyt Are you still experiencing some problems that need to be addressed for the review?

**Comment by cthoyt** [comment]
@hechth sorry I seemed to miss your comment before. Pip install works great now!
