### ISSUE TITLE
[JOSS Review] Automated tests: some automated tests fail

### ISSUE THREAD

**Issue by davidegraff** [RECETOX/RIAssigner#89]
*cc https://github.com/openjournals/joss-reviews/issues/4337*

After setting up the `riassigner-dev` environment and installing `RIAssigner` according to the [instructions in the README](https://github.com/RECETOX/RIAssigner/#installation), I ran:

```$ pytest > pytest.log```

and some of the tests failed. I have attached the output here: [pytest.log](https://github.com/RECETOX/RIAssigner/files/8755334/pytest.log)

**Comment by hechth** [comment]
@davidegraff please check out the PR #90 - this should solve those issues.

Please feel free to comment here or on the PR! Thank you very much!
